version: "3.8"
networks:
  dev-net:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  application:
    build: ./<app>/
    networks:
      - dev-net    
    environment:
      - 'MONGODB_URI=mongodb://mongodb:27017/db'
      - 'KAFKA_HOST=kafka-server:9092'
    ports:
      - "8018:8018"

  mongodb:
    image: "mongo:3.6.20-xenial"
    networks:
      - dev-net    
  
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - dev-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - dev-net    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  
  prometheus:
    image: prom/prometheus:v2.22.0-rc.0
    networks:
      - dev-net    
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        -  prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    

  grafana:
    image: grafana/grafana:6.5.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
        - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - dev-net    



  
      
  # kafka-server2:
  #   image: 'bitnami/kafka:latest'
  #   networks:
  #     - dev-net    
  #   ports:
  #     - '9093:9092'
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper-server
