global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'publisher-api'
    static_configs:
      - targets: ['publisher-api:8084']
